spring.application.name=premier-zone
spring.datasource.url=jdbc:mysql://localhost:3306/premier_league
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none    
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8081


# يطبع القيم اللي بتتبعت في الـ Query
logging.level.org.hibernate.orm.queries=DEBUG